import './globals.css';
import type { Metadata, NextComponentType } from 'next';
import { Inter } from 'next/font/google';
import MainProvider from '@/providers/MainProvider';
import { ReactNode } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <MainProvider>
        <body className={inter.className}>{children}</body>
      </MainProvider>
    </html>
  );
}
