import './globals.css';
import type { Metadata, NextComponentType } from 'next';
import { Inter } from 'next/font/google';
import MainProvider from '@/providers/MainProvider';
import { ReactNode } from 'react';
import NavBar from '@/widgets/navbar/NavBar';
import Layout from '@/widgets/layout/layout';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainProvider>
          <Layout>{children}</Layout>
        </MainProvider>
      </body>
    </html>
  );
}
