import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import MainProvider from '@/app/providers/MainProvider';
import { ReactNode } from 'react';
import Layout from '@/widgets/layout/layout';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainProvider>
          <Layout>{children}</Layout>
        </MainProvider>
      </body>
    </html>
  );
}
