name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_REMOTE_ADDRESS }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          script: |
            sudo rm -rf tg_web_app
            sudo gh repo clone Monitozation/tg_web_app
            sudo cd tg_web_app
            sudo docker stop ${{ secrets.DOCKER_REPO_NAME }} || true
            sudo docker rm ${{ secrets.DOCKER_REPO_NAME }} || true
            touch .env
            echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" >> .env
            echo "NEXT_PUBLIC_UPLOADS_URL=${{ secrets.NEXT_PUBLIC_UPLOADS_URL }}" >> .env
            echo "NEXT_PUBLIC_SOCKET_URL=${{ secrets.NEXT_PUBLIC_SOCKET_URL }}" >> .env
            echo "NEXT_PUBLIC_BOT_LINK=${{ secrets.NEXT_PUBLIC_BOT_LINK }}" >> .env
            sudo docker build -t ${{ secrets.DOCKER_REPO_NAME }} .
            sudo docker run -d --name ${{ secrets.DOCKER_REPO_NAME }} -p 3000:3000
      
